---
# Change the profile and region to suit your application
profile: bjacobel
region: us-east-1
iam:
  policy:
    name: AWSLambdaBasicExecutionRole
  role:
    name: lambda_basic_execution
lambda:
  name: BosFoodFails
  zipfile_name: bff.zip
  description: Polls https://data.cityofboston.gov/resource/qndu-wx8w.json, finds new violations in the last day
  path: bff.py
  handler: lambda_handler
  runtime: python2.7
  memory_size: 128
  timeout: 10
  mode: event
  test_data: input.json
